name: IMLO-Coursework
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - tqdm
  - pandas=2.2.2           
  - scikit-learn=1.4.2     
  - pytorch=2.2.0
  - torchvision=0.17.0