name: IMLO-Coursework
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - torchvision
  - pytorch[version='>=2.6.0']
  - matplotlib
  - tqdm
  - pip:
      - pandas==2.2.3
